# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20151228_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allocation',
            field=models.FloatField(default=0),
        ),
    ]
