# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set([('name', 'price')]),
        ),
    ]
