# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_auto_20160123_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(default=b'client', max_length=128)),
                ('address', models.CharField(default=b'Australia', max_length=512)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='calc.Job'),
            preserve_default=False,
        ),
    ]
