# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0017_auto_20160202_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'General', max_length=128)),
            ],
        ),
    ]
