# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0018_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(default=b'General', max_length=128, unique=True),
        ),
    ]
