# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0020_invoice_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.Stage'),
        ),
    ]
