# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0021_auto_20160211_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calc.Job'),
        ),
    ]
