# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0022_invoice_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='site',
            field=models.IntegerField(default=0),
        ),
    ]
